Projeto_Erik_Abdala/config/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from app.views import *
from app import views

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name = 'index.html'), name = 'index'),
    path('areas/', area, name = 'areas'),
    path('fisicos/', fisico, name = 'fisicos'),
    path('invencoes/', invencao, name = 'invencoes'),
    path('subareas/', subarea, name = 'subareas'),
    path('pessoas/', pessoa, name = 'pessoa'),

    path("topicos/", TopicoListView.as_view(), name = 'topicoList'),
    path("topicos/<int:pk>/", TopicoDetailView.as_view(), name = 'topicoDetail'),

    path("questionarios/", QuestionarioListView.as_view(), name = 'questionarioList'),
    path("questionarios/<int:pk>/", QuestionarioDetailView.as_view(), name = 'questionarioDetail'),

    path("feedback/<int:questionario_id>/", views.submeter_respostas, name = 'submeter_respostas'),

    path('envios/', respondido, name = 'respondidos'),

]

Projeto_Erik_Abdala/app/models.py
from django.db import models

# Create your models here.

class Area(models.Model):

    nome = models.CharField(max_length = 80, verbose_name="Nome")
    descricao = models.CharField(max_length = 300, verbose_name="Descrição")

    class Meta:

        verbose_name = "Área"
        verbose_name_plural = "Áreas"

    def __str__(self):

        return f'{self.nome}'
    
class Subarea(models.Model):

    nome = models.CharField(max_length = 80, verbose_name="Nome")
    descricao = models.CharField(max_length = 300, verbose_name="Descrição")
    area = models.ForeignKey(Area, on_delete = models.CASCADE, verbose_name="Área")

    class Meta:

        verbose_name = "Subárea"
        verbose_name_plural = "Subáreas"

    def __str__(self):

        return f'{self.area} - {self.nome}'
    
class Topico(models.Model):

    nome = models.CharField(max_length = 80, verbose_name="Nome")
    descricao = models.CharField(max_length = 2000, verbose_name="Descrição")
    subarea = models.ForeignKey(Subarea, on_delete = models.CASCADE, verbose_name="Subárea")

    class Meta:

        verbose_name = "Tópico"
        verbose_name_plural = "Tópicos"

    def __str__(self):

        return f'[{self.subarea}] - {self.nome}'
    
class Questionario(models.Model):

    titulo = models.CharField(max_length = 80, verbose_name="Título")
    descricao = models.CharField(max_length = 300, verbose_name="Descrição")
    area = models.ForeignKey(Area, on_delete = models.CASCADE, verbose_name="Área")

    class Meta:

        verbose_name = "Questionário"
        verbose_name_plural = "Questionários"

    def __str__(self):

        return f'[{self.area}] - {self.titulo}'
    
class Questao(models.Model):

    questionario = models.ForeignKey(Questionario, on_delete = models.CASCADE, verbose_name="Questionário")
    titulo = models.CharField(max_length = 80, verbose_name="Título")
    enunciado = models.CharField(max_length = 500, verbose_name="Enunciado")
    alternativa_a = models.CharField(max_length = 300, verbose_name="Alternativa A")
    alternativa_b = models.CharField(max_length = 300, verbose_name="Alternativa B")
    alternativa_c = models.CharField(max_length = 300, verbose_name="Alternativa C")
    alternativa_d = models.CharField(max_length = 300, verbose_name="Alternativa D")
    alternativa_e = models.CharField(max_length = 300, verbose_name="Alternativa E")
    alternativa_correta = models.CharField(max_length = 1, verbose_name="Alternativa correta")

    class Meta:

        verbose_name = "Questão"
        verbose_name_plural = "Questões"

    def __str__(self):

        return f'{self.titulo}'
    
class Ocupacao(models.Model):

    nome = models.CharField(max_length = 30, verbose_name="Nome")

    class Meta:

        verbose_name = "Ocupação"
        verbose_name_plural = "Ocupações"

    def __str__(self):

        return f'{self.nome}'
    
class Pessoa(models.Model):

    nome = models.CharField(max_length = 80, verbose_name="Nome")
    ocupacao = models.ForeignKey(Ocupacao, on_delete = models.CASCADE, verbose_name="Ocupação")

    class Meta:

        verbose_name = "Pessoa"
        verbose_name_plural = "Pessoas"

    def __str__(self):

        return f'[{self.ocupacao}] - {self.nome}'
    
class Integrante(Pessoa):

    email = models.CharField(max_length = 50, verbose_name="Email")

    class Meta:

        verbose_name = "Integrante"
        verbose_name_plural = "Integrantes"

    def __str__(self):

        return f'{self.nome}'
    
class Fisico(Pessoa):

    biografia = models.CharField(max_length = 300, verbose_name="Biografia")
    data_nascimento = models.DateField(verbose_name="Data de nascimento")

    class Meta:

        verbose_name = "Físico"
        verbose_name_plural = "Físicos"

    def __str__(self):

        return f'{self.nome}'
    
class Invencao(models.Model):

    nome = models.CharField(max_length = 80, verbose_name="Nome")
    ano = models.DateField(verbose_name="Ano")
    fisico = models.ManyToManyField(Fisico, verbose_name="Físico")
    area = models.ManyToManyField(Area, verbose_name="Área")

    class Meta:

        verbose_name = "Invenção"
        verbose_name_plural = "Invenções"

    def __str__(self):

        return f'{self.nome}'
    
class QuestionarioRespondido(models.Model):

    questionario = models.ForeignKey(Questionario, on_delete = models.CASCADE, verbose_name="Questionário")
    pessoa = models.ForeignKey(Pessoa, on_delete = models.CASCADE, verbose_name="Pessoa")
    data_realizacao = models.DateTimeField(verbose_name="Data de realização")
    numero_acertos = models.PositiveIntegerField(verbose_name="Número de acertos")
    respostas_pessoa = models.TextField(blank = True, null = True, verbose_name="Respostas da pessoa")

    class Meta:

        verbose_name = "Questionário respondido"
        verbose_name_plural = "Questionários respondidos"

    def __str__(self):

        return f'{self.questionario} {self.pessoa}'

Projeto_Erik_Abdala/app/templates/exibicao/questionario/questionario-detail.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  <title>IFisica | Questionários | {{ questionario.id }}</title>
  <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.png' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <a href="/"><img src="{% static 'img/favicon.png' %}" width="30" height="30" class="d-inline-block align-top" alt="" style="margin-right: 8px;"></a>
    <a class="navbar-brand" href="/">IFisica</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link text-dark" href="/">Home</a>
          </li>
        <div class = "dropdown">
        <button class = "nav-link text-dark dropbtn">Áreas<i class = "arrow down"></i></button>
        <div class = "dropdown-content">
          <a href = "/areas">Áreas</a>
          <a href = "/subareas">Subáreas</a>
          <a href = "/topicos">Tópicos</a>
        </div>
        </div>
        <div class = "dropdown">
        <button class = "nav-link text-dark dropbtn">Invenções<i class = "arrow down"></i></button>
        <div class = "dropdown-content">
          <a href = "/invencoes">Invenções</a>
          <a href = "/fisicos">Físicos</a>
        </div>
        </div>
        <div class = "dropdown">
        <button class = "nav-link text-dark dropbtn">Questionários<i class = "arrow down"></i></button>
        <div class = "dropdown-content">
          <a href="/questionarios">Questionários</a>
          <a href="/envios">Envios</a>
        </div>
        </div>
        <li class="nav-item">
          <a class="nav-link text-dark" href="/pessoas">Integrantes</a>
        </li>
        <li id = "adm" class="nav-item">
          <a class="nav-link text-dark" href="/admin/">Administração</a>
        </li>
      </ul>
    </div>
  </nav>
  
  <div class="container mt-5">
    <h2 style = "text-align: center;" class="mb-4 quebra">{{ questionario.area }}</h2>
    <h4 class="quebra" style="margin-bottom: 20px;">{{ questionario.id }} - {{ questionario.titulo }}</h4>
    <p class="quebra" style="margin-bottom: 30px;">{{ questionario.descricao }}</p>
    {% for Questao in questionario.questao_set.all %}
    <form name = "Formulario" method = "post" action = "{% url 'submeter_respostas' questionario.id %}">{% csrf_token %}
        <h5 class="quebra" style="margin-bottom: 15px;">{{ forloop.counter }} - {{ Questao.titulo }}</h5>
        <p style="font-weight: normal; word-wrap: break-word;">{{ Questao.enunciado}}</p>
        <input type = 'radio' placeholder = "Questão 1-A" name = "Q{{ Questao.id }}" value = "A">
        <label for = "Q{{ Questao.id }}A"><span class="quebra">{{ Questao.alternativa_a }}</span></label><br>
        <input type = 'radio' placeholder = "Questão 1-B" name = "Q{{ Questao.id }}" value = "B">
        <label for = "Q{{ Questao.id }}B"><span class="quebra">{{ Questao.alternativa_b }}</span></label><br>
        <input type = 'radio' placeholder = "Questão 1-C" name = "Q{{ Questao.id }}" value = "C">
        <label for = "Q{{ Questao.id }}C"><span class="quebra">{{ Questao.alternativa_c }}</span></label><br>
        <input type = 'radio' placeholder = "Questão 1-D" name = "Q{{ Questao.id }}" value = "D">
        <label for = "Q{{ Questao.id }}D"><span class="quebra">{{ Questao.alternativa_d }}</span></label><br>
        <input type = 'radio' placeholder = "Questão 1-E" name = "Q{{ Questao.id }}" value = "E">
        <label for = "Q{{ Questao.id }}E"><span class="quebra">{{ Questao.alternativa_e }}</span></label><br>
        <div style="margin-bottom: 20px;"></div>
    {% endfor %}
        <div class = "form-group" style="margin-bottom: 30px;">
            <label for = "membro"><b>Nome:</b></label>
            <select class = "form-control" id="membro" name = "membro" style="width: 30%;">
            {% for Pessoa in membros %}
                <option value="{{ Pessoa.id }}">{{ Pessoa.nome }}</option>
            {% endfor %}
            </select>
        </div>
    <input type = "submit" value = "Enviar">
    </form>
  </div>

  <div style="margin-bottom: 60px;"></div>

  <!-- Incluindo jQuery e Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

Projeto_Erik_Abdala/app/templates/exibicao/questionario/questionario-list.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  <title>IFisica | Questionários</title>
  <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.png' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <a href="/"><img src="{% static 'img/favicon.png' %}" width="30" height="30" class="d-inline-block align-top" alt="" style="margin-right: 8px;"></a>
    <a class="navbar-brand" href="/">IFisica</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link text-dark" href="/">Home</a>
          </li>
        <div class = "dropdown">
        <button class = "nav-link text-dark dropbtn">Áreas<i class = "arrow down"></i></button>
        <div class = "dropdown-content">
          <a href = "/areas">Áreas</a>
          <a href = "/subareas">Subáreas</a>
          <a href = "/topicos">Tópicos</a>
        </div>
        </div>
        <div class = "dropdown">
        <button class = "nav-link text-dark dropbtn">Invenções<i class = "arrow down"></i></button>
        <div class = "dropdown-content">
          <a href = "/invencoes">Invenções</a>
          <a href = "/fisicos">Físicos</a>
        </div>
        </div>
        <div class = "dropdown">
        <button class = "nav-link text-dark dropbtn">Questionários<i class = "arrow down"></i></button>
        <div class = "dropdown-content">
          <a href="/questionarios">Questionários</a>
          <a href="/envios">Envios</a>
        </div>
        </div>
        <li class="nav-item">
          <a class="nav-link text-dark" href="/pessoas">Integrantes</a>
        </li>
        <li id = "adm" class="nav-item">
          <a class="nav-link text-dark" href="/admin/">Administração</a>
        </li>
      </ul>
    </div>
  </nav>
  
  <div class="container mt-5">
    <h2 style = "text-align: center;" class="mb-4">Questionários</h2>
    <ul class = "teste3-1">
        {% for Questionario in questionarios %}
        <li class = "teste3-2 quebra">{{ Questionario.id }} - <a href="{% url 'questionarioDetail' Questionario.pk %}">[{{ Questionario.area }}] - {{ Questionario.titulo }}</a></li>
        {% endfor %}
    </ul>
  </div>

  <div style="margin-bottom: 60px;"></div>

  <!-- Incluindo jQuery e Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>