Projeto_Erik_Abdala/config/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from app.views import *
from app import views

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name = 'index.html'), name = 'index'),
    path('areas/', area, name = 'areas'),
    path('fisicos/', fisico, name = 'fisicos'),
    path('invencoes/', invencao, name = 'invencoes'),
    path('subareas/', subarea, name = 'subareas'),
    path('pessoas/', pessoa, name = 'pessoa'),

    path("topicos/", TopicoListView.as_view(), name = 'topicoList'),
    path("topicos/<int:pk>/", TopicoDetailView.as_view(), name = 'topicoDetail'),

    path("questionarios/", QuestionarioListView.as_view(), name = 'questionarioList'),
    path("questionarios/<int:pk>/", QuestionarioDetailView.as_view(), name = 'questionarioDetail'),

    path("feedback/<int:questionario_id>/", views.submeter_respostas, name = 'submeter_respostas'),

    path('envios/', respondido, name = 'respondidos'),

]

Projeto_Erik_Abdala/app/models.py
from django.db import models

# Create your models here.

class Area(models.Model):

    nome = models.CharField(max_length = 80, verbose_name="Nome")
    descricao = models.CharField(max_length = 300, verbose_name="Descrição")

    class Meta:

        verbose_name = "Área"
        verbose_name_plural = "Áreas"

    def __str__(self):

        return f'{self.nome}'
    
class Subarea(models.Model):

    nome = models.CharField(max_length = 80, verbose_name="Nome")
    descricao = models.CharField(max_length = 300, verbose_name="Descrição")
    area = models.ForeignKey(Area, on_delete = models.CASCADE, verbose_name="Área")

    class Meta:

        verbose_name = "Subárea"
        verbose_name_plural = "Subáreas"

    def __str__(self):

        return f'{self.area} - {self.nome}'
    
class Topico(models.Model):

    nome = models.CharField(max_length = 80, verbose_name="Nome")
    descricao = models.CharField(max_length = 2000, verbose_name="Descrição")
    subarea = models.ForeignKey(Subarea, on_delete = models.CASCADE, verbose_name="Subárea")

    class Meta:

        verbose_name = "Tópico"
        verbose_name_plural = "Tópicos"

    def __str__(self):

        return f'[{self.subarea}] - {self.nome}'
    
class Questionario(models.Model):

    titulo = models.CharField(max_length = 80, verbose_name="Título")
    descricao = models.CharField(max_length = 300, verbose_name="Descrição")
    area = models.ForeignKey(Area, on_delete = models.CASCADE, verbose_name="Área")

    class Meta:

        verbose_name = "Questionário"
        verbose_name_plural = "Questionários"

    def __str__(self):

        return f'[{self.area}] - {self.titulo}'
    
class Questao(models.Model):

    questionario = models.ForeignKey(Questionario, on_delete = models.CASCADE, verbose_name="Questionário")
    titulo = models.CharField(max_length = 80, verbose_name="Título")
    enunciado = models.CharField(max_length = 500, verbose_name="Enunciado")
    alternativa_a = models.CharField(max_length = 300, verbose_name="Alternativa A")
    alternativa_b = models.CharField(max_length = 300, verbose_name="Alternativa B")
    alternativa_c = models.CharField(max_length = 300, verbose_name="Alternativa C")
    alternativa_d = models.CharField(max_length = 300, verbose_name="Alternativa D")
    alternativa_e = models.CharField(max_length = 300, verbose_name="Alternativa E")
    alternativa_correta = models.CharField(max_length = 1, verbose_name="Alternativa correta")

    class Meta:

        verbose_name = "Questão"
        verbose_name_plural = "Questões"

    def __str__(self):

        return f'{self.titulo}'
    
class Ocupacao(models.Model):

    nome = models.CharField(max_length = 30, verbose_name="Nome")

    class Meta:

        verbose_name = "Ocupação"
        verbose_name_plural = "Ocupações"

    def __str__(self):

        return f'{self.nome}'
    
class Pessoa(models.Model):

    nome = models.CharField(max_length = 80, verbose_name="Nome")
    ocupacao = models.ForeignKey(Ocupacao, on_delete = models.CASCADE, verbose_name="Ocupação")

    class Meta:

        verbose_name = "Pessoa"
        verbose_name_plural = "Pessoas"

    def __str__(self):

        return f'[{self.ocupacao}] - {self.nome}'
    
class Integrante(Pessoa):

    email = models.CharField(max_length = 50, verbose_name="Email")

    class Meta:

        verbose_name = "Integrante"
        verbose_name_plural = "Integrantes"

    def __str__(self):

        return f'{self.nome}'
    
class Fisico(Pessoa):

    biografia = models.CharField(max_length = 300, verbose_name="Biografia")
    data_nascimento = models.DateField(verbose_name="Data de nascimento")

    class Meta:

        verbose_name = "Físico"
        verbose_name_plural = "Físicos"

    def __str__(self):

        return f'{self.nome}'
    
class Invencao(models.Model):

    nome = models.CharField(max_length = 80, verbose_name="Nome")
    ano = models.DateField(verbose_name="Ano")
    fisico = models.ManyToManyField(Fisico, verbose_name="Físico")
    area = models.ManyToManyField(Area, verbose_name="Área")

    class Meta:

        verbose_name = "Invenção"
        verbose_name_plural = "Invenções"

    def __str__(self):

        return f'{self.nome}'
    
class QuestionarioRespondido(models.Model):

    questionario = models.ForeignKey(Questionario, on_delete = models.CASCADE, verbose_name="Questionário")
    pessoa = models.ForeignKey(Pessoa, on_delete = models.CASCADE, verbose_name="Pessoa")
    data_realizacao = models.DateTimeField(verbose_name="Data de realização")
    numero_acertos = models.PositiveIntegerField(verbose_name="Número de acertos")
    respostas_pessoa = models.TextField(blank = True, null = True, verbose_name="Respostas da pessoa")

    class Meta:

        verbose_name = "Questionário respondido"
        verbose_name_plural = "Questionários respondidos"

    def __str__(self):

        return f'{self.questionario} {self.pessoa}'

Projeto_Erik_Abdala/app/templates/exibicao/topico/topico-detail.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  <title>IFisica | Tópicos | {{ topico.nome }}</title>
  <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.png' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <a href="/"><img src="{% static 'img/favicon.png' %}" width="30" height="30" class="d-inline-block align-top" alt="" style="margin-right: 8px;"></a>
    <a class="navbar-brand" href="/">IFisica</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link text-dark" href="/">Home</a>
          </li>
        <div class = "dropdown">
        <button class = "nav-link text-dark dropbtn">Áreas<i class = "arrow down"></i></button>
        <div class = "dropdown-content">
          <a href = "/areas">Áreas</a>
          <a href = "/subareas">Subáreas</a>
          <a href = "/topicos">Tópicos</a>
        </div>
        </div>
        <div class = "dropdown">
        <button class = "nav-link text-dark dropbtn">Invenções<i class = "arrow down"></i></button>
        <div class = "dropdown-content">
          <a href = "/invencoes">Invenções</a>
          <a href = "/fisicos">Físicos</a>
        </div>
        </div>
        <div class = "dropdown">
        <button class = "nav-link text-dark dropbtn">Questionários<i class = "arrow down"></i></button>
        <div class = "dropdown-content">
          <a href="/questionarios">Questionários</a>
          <a href="/envios">Envios</a>
        </div>
        </div>
        <li class="nav-item">
          <a class="nav-link text-dark" href="/pessoas">Integrantes</a>
        </li>
        <li id = "adm" class="nav-item">
          <a class="nav-link text-dark" href="/admin/">Administração</a>
        </li>
      </ul>
    </div>
  </nav>

  <style>

    .estilof {
      font-family: Arial, Helvetica, sans-serif;
      font-size: medium;
    }

  </style>

  <div class="container mt-5">
    <h2 style = "text-align: center;" class="mb-4 quebra">{{ topico.nome }}</h2>
    <tbody>
        <h4 style="margin-bottom: 25px;" class="quebra">{{ topico.subarea }}</h4>
        <pre style="white-space: pre-wrap;"><p class="quebra estilof">{{ topico.descricao }}</p></pre>
    </tbody>
  </div>

  <div style="margin-bottom: 60px;"></div>

  <!-- Incluindo jQuery e Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

Projeto_Erik_Abdala/app/templates/exibicao/topico/topico-list.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  <title>IFisica | Tópicos</title>
  <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.png' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <a href="/"><img src="{% static 'img/favicon.png' %}" width="30" height="30" class="d-inline-block align-top" alt="" style="margin-right: 8px;"></a>
    <a class="navbar-brand" href="/">IFisica</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link text-dark" href="/">Home</a>
          </li>
        <div class = "dropdown">
        <button class = "nav-link text-dark dropbtn">Áreas<i class = "arrow down"></i></button>
        <div class = "dropdown-content">
          <a href = "/areas">Áreas</a>
          <a href = "/subareas">Subáreas</a>
          <a href = "/topicos">Tópicos</a>
        </div>
        </div>
        <div class = "dropdown">
        <button class = "nav-link text-dark dropbtn">Invenções<i class = "arrow down"></i></button>
        <div class = "dropdown-content">
          <a href = "/invencoes">Invenções</a>
          <a href = "/fisicos">Físicos</a>
        </div>
        </div>
        <div class = "dropdown">
        <button class = "nav-link text-dark dropbtn">Questionários<i class = "arrow down"></i></button>
        <div class = "dropdown-content">
          <a href="/questionarios">Questionários</a>
          <a href="/envios">Envios</a>
        </div>
        </div>
        <li class="nav-item">
          <a class="nav-link text-dark" href="/pessoas">Integrantes</a>
        </li>
        <li id = "adm" class="nav-item">
          <a class="nav-link text-dark" href="/admin/">Administração</a>
        </li>
      </ul>
    </div>
  </nav>

  <div class="container mt-5">
    <h2 style = "text-align: center;" class="mb-4">Tópicos</h2>
    {% for Area in areas %}
    <button class="collapsible quebra">{{ Area.nome }}</button>
    <div class="content">
      {% for Subarea in Area.subarea_set.all %}
      <button class="collapsible level-2 quebra">{{ Subarea.nome }}</button>
      <div class="content" style = "margin-left: 50px;">
        {% for Topico in Subarea.topico_set.all %}
        <a href = "{% url 'topicoDetail' Topico.pk %}"><p class="quebra">{{ Topico.nome }}</p></a>
        {% endfor %}
      </div>
      {% endfor %}
    </div>
    {% endfor %}
  </div>

  <div style="margin-bottom: 60px;"></div>

  <!-- Script para fazer o collapsible funcionar -->
  <script>
    var coll = document.getElementsByClassName("collapsible");
    var i;

    for (i = 0; i < coll.length; i++) {
      coll[i].addEventListener("click", function() {
        this.classList.toggle("active");
        var content = this.nextElementSibling;
        if (content.style.display === "block") {
          content.style.display = "none";
        } else {
          content.style.display = "block";
        }
      });
    }
  </script>

  <!-- Incluindo jQuery e Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>